spring.application.name=simulateur-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/simulateur_salle_marche
spring.datasource.username=simulateur_app
spring.datasource.password=${DB_PASSWORD}

spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8

app.frontend.base-url=http://localhost:4200